---

- name: Create directory {{ rsnapshot_snapshot_root }}
  file: >
    path="{{ rsnapshot_snapshot_root }}"
    state="directory"
    owner="{{ rsnapshot_snapshot_root_owner }}"
    group="{{ rsnapshot_snapshot_root_group }}"
    mode="{{ rsnapshot_snapshot_root_mode }}"

- name: Create configuration {{ rsnapshot_config_file }}
  template: >
    src="rsnapshot.conf.j2"
    dest="{{ rsnapshot_config_file }}"
    owner="{{ rsnapshot_config_file_owner }}"
    group="{{ rsnapshot_config_file_group }}"
    mode="{{ rsnapshot_config_file_mode }}"
    backup="yes"
    validate="rsnapshot -c %s configtest"

- name: Create test directory {{ rsnapshot_snapshot_root_test }}
  file: >
    path="{{ rsnapshot_snapshot_root_test }}"
    state="directory"
    owner="{{ rsnapshot_snapshot_root_owner }}"
    group="{{ rsnapshot_snapshot_root_group }}"
    mode="{{ rsnapshot_snapshot_root_mode }}"
  when: rsnapshot_test|lower == "yes"

- name: Create test backup_points
  file: >
    path="{{ item.dir }}"
    state="directory"
    owner="{{ rsnapshot_snapshot_root_owner }}"
    group="{{ rsnapshot_snapshot_root_group }}"
    mode="{{ rsnapshot_snapshot_root_mode }}"
  with_items: "{{ rsnapshot_backup_points_test }}"
  when: rsnapshot_test|lower == "yes"

- name: Create test configuration {{ rsnapshot_config_file_test }}
  template: >
    src="rsnapshot-test.conf.j2"
    dest="{{ rsnapshot_config_file_test }}"
    owner="{{ rsnapshot_config_file_owner }}"
    group="{{ rsnapshot_config_file_group }}"
    mode="{{ rsnapshot_config_file_mode }}"
    backup="yes"
    validate="rsnapshot -c %s configtest"
  when: rsnapshot_test|lower == "yes"

# EOF
...
