---

- name: Create configuration {{ rsnapshot_config_file }}
  template: >
    src="rsnapshot.conf.j2"
    dest="{{ rsnapshot_config_file }}"
    owner="{{ rsnapshot_config_file_owner }}"
    group="{{ rsnapshot_config_file_group }}"
    mode="{{ rsnapshot_config_file_mode }}"
    backup="yes"
    validate="rsnapshot -c %s configtest"

# EOF
...
