---

- name: Add {{ ansible_os_family }} specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: rsnapshot_vars

- import_tasks: packages.yml
  tags: rsnapshot_packages

- import_tasks: configure.yml
  tags: rsnapshot_config

# EOF
...
