---

- name: Add {{ansible_os_family}} specific variables
  include_vars: "{{ansible_os_family}}.yml"
  tags:
    - rsnapshot_variables
    - rsnapshot_all

- include: packages.yml
  tags:
    - rsnapshot_packages
    - rsnapshot_all

- include: configure.yml
  tags:
    - rsnapshot_configure
    - rsnapshot_all

# EOF
...
