---

- import_tasks: vars.yml
  tags: [rsnapshot_vars, always]

- import_tasks: debug.yml
  when: rsnapshot_debug|bool
  tags: [rsnapshot_debug, always]

- import_tasks: packages.yml
  when: rsnapshot_install|bool
  tags: rsnapshot_packages

- import_tasks: configure.yml
  tags: rsnapshot_config

- import_tasks: test.yml
  when: rsnapshot_test
  tags: rsnapshot_test

# EOF
...
