---

- name: "Debug"
  debug:
    msg: "ansible_os_family [{{ ansible_os_family }}]"
  when: rsnapshot_debug

- name: "Include variables from vars/{{ ansible_os_family }}"
  include_vars: "{{ ansible_os_family }}.yml"
  tags: [rsnapshot_vars, always]

- import_tasks: packages.yml
  when: rsnapshot_install|bool
  tags: rsnapshot_packages

- import_tasks: configure.yml
  tags: rsnapshot_config

- import_tasks: test.yml
  when: rsnapshot_test
  tags: rsnapshot_test

# EOF
...
