---

#- debug: msg="{{ ansible_os_family }}"

# FreeBSD
- name: Install packages
  pkgng: >
    name="{{ item }}"
    state="present"
  with_items: "{{ rsnapshot_packages }}"
  when: (ansible_os_family == "FreeBSD") and (freebsd_install_method == "packages")

- name: Install ports
  portinstall: >
    name="{{ item }}"
    state="present"
    use_packages="{{ freebsd_use_packages }}"
  with_items: "{{ rsnapshot_packages }}"
  when: (ansible_os_family == "FreeBSD") and (freebsd_install_method == "ports")

# Debian
- name: Install packages
  apt: >
    name="{{ item }}"
    state="installed"
  with_items: "{{ rsnapshot_packages }}"
  when: ansible_os_family == "Debian"
        
# RedHat
- name: Install packages
  yum: >
    name="{{ item }}"
    state="installed"
  with_items: "{{ rsnapshot_packages }}"
  when: ansible_os_family == "RedHat"
  
# EOF
...
