---

- name: "systemd-timers: Install rsnapshot service"
  template:
    src: "rsnapshot@.service.j2"
    dest: "/etc/systemd/system/rsnapshot{{ rsnapshot_systemd_postfix  }}@.service"
    owner: root
    group: root
    mode: '0644'
  tags: rsnapshot_systemd_timers_service

- name: "systemd-timers: Install rsnapshot timers"
  template:
    src: "rsnapshot-{{ item }}.timer.j2"
    dest: "/etc/systemd/system/rsnapshot{{ rsnapshot_systemd_postfix  }}-{{ item }}.timer"
    owner: root
    group: root
    mode: '0644'
  loop:
    - monthly
    - weekly
    - daily
    - hourly
  tags: rsnapshot_systemd_timers_install

- name: "systemd-timers: Enable rsnapshot timers"
  systemd:
    name: "rsnapshot{{ rsnapshot_systemd_postfix  }}-{{ item }}.timer"
    daemon_reload: true
    enabled: true
    masked: false
    state: restarted
  loop:
    - monthly
    - weekly
    - daily
    - hourly
  when: "lookup('vars', 'rsnapshot_retain_' ~ item) != '-1'"
  tags: rsnapshot_systemd_timers_enable

- name: "systemd-timers: Disable rsnapshot timers"
  systemd:
    name: "rsnapshot{{ rsnapshot_systemd_postfix  }}-{{ item }}.timer"
    daemon_reload: true
    enabled: false
    masked: true
    state: stopped
  loop:
    - monthly
    - weekly
    - daily
    - hourly
  when: "lookup('vars', 'rsnapshot_retain_' ~ item) == '-1'"
  tags: rsnapshot_systemd_timers_disable

- name: "systemd-timers: Get systemd-timers"  # noqa 303
  command: systemctl list-timers
  register: result
  when: rsnapshot_debug|bool
  tags: rsnapshot_systemd_timers_debug

- name: "systemd-timers: Display systemd-timers"
  debug:
    var: result.stdout_lines
  when: rsnapshot_debug|bool
  tags: rsnapshot_systemd_timers_debug


# EOF
...
